# Generated by Django 4.2 on 2024-09-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('mag_x', models.FloatField()),
                ('mag_y', models.FloatField()),
                ('mag_z', models.FloatField()),
                ('barometro', models.FloatField()),
                ('ruido', models.FloatField()),
                ('giro_x', models.FloatField()),
                ('giro_y', models.FloatField()),
                ('giro_z', models.FloatField()),
                ('acel_x', models.FloatField()),
                ('acel_y', models.FloatField()),
                ('acel_z', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
